### ISSUE TITLE
cleanup: use the prerelease feature instead of custom owlbot override

### ISSUE THREAD

**Issue by tswast** [googleapis/python-db-dtypes-pandas#150]
Much of the code in owlbot.py might be able to be removed by migrating to the new prerelease session available in the templates. https://github.com/googleapis/synthtool/pull/1455

**Comment by tswast** [comment]
Some modification might still be required to use the nightlies we need.

**Comment by chalmerlowe** [comment]
Closing. Looking to deprecate this library in the future.
