### ISSUE TITLE
Support python 3.11

### ISSUE THREAD

**Issue by oliviernguyenquoc** [googleapis/python-db-dtypes-pandas#172]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**

The package is not compatible with python 3.11 (cf setup.py)

 **Describe the solution you'd like**

Check compatibility and update setup.py to allow python 3.11 version

 **Describe alternatives you've considered**

 **Additional context**

**Comment by tswast** [comment]
Fixed by https://github.com/googleapis/python-db-dtypes-pandas/pull/145 ?

**Comment by chalmerlowe** [comment]
Fixed by #145
