### ISSUE TITLE
"pip install db-dtypes" fails

### ISSUE THREAD

**Issue by jtiscione** [googleapis/python-db-dtypes-pandas#226]
If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - Linux, using miniconda3
  - Python version: 3.10.3
  - pip version: 23.3
  - `db-dtypes` version: N/A

#### Steps to reproduce

  1. pip install db-dtypes

ERROR: Could not find a version that satisfies the requirement db-dtypes (from versions: none)
ERROR: No matching distribution found for db-dtypes

Also tried conda, pip3, etc.

**Comment by gariepyalex** [comment]
I'm also currently having the issue. Weirdly enough, db-types doesn't who up in pypi's search:
https://pypi.org/search/?q=db-types&o=
<img width="1239" alt="image" src="https://github.com/googleapis/python-db-dtypes-pandas/assets/6105461/f50020d1-7e65-47b3-8fe5-649428ee2d72">
