### ISSUE TITLE
WhiteSource Issue with pyarrow 12.0.1 in db_dttypes 1.2.0 Transitive Dependency

### ISSUE THREAD

**Issue by rakesh-sanyashiv** [googleapis/python-db-dtypes-pandas#250]
Encountering a WhiteSource issue related to the transitive dependency of pyarrow version 12.0.1 within the db_dttypes library version 1.2.0. Despite upgrading pyarrow as recommended, the issue persists.

**Comment by Linchin** [comment]
Hi @rakesh-sanyashiv, thank you for reporting this issue! Could you tell me more about the details of this bug, such as the steps to reproduce it, and the error message or error tracing? This will help us pin point the issue with no ambiguity. Thank you!

**Comment by rakesh-sanyashiv** [comment]
Thank you for your response.

We have identified a critical issue within our Python service that utilizes the latest version of db-dttypes. During the code scan conducted with WhiteSource Mend, critical vulnerabilities were flagged for pyarrow-12.0.1. Upon further investigation, it was revealed that these vulnerabilities are associated with the pyarrow-12.0.1 version embedded in db-dttypes.

As a recommended solution, we propose upgrading the pyarrow version within db-dttypes to address and resolve these identified vulnerabilities. This proactive step will contribute to the overall security and stability of our Python service.

Your attention to this matter is greatly appreciated. If you have any further questions or require additional information, please don't hesitate to reach out.

[cid:0614bc02-3d9d-41dd-a785-ba1492c02e72]



Rakesh Sanyashiv

Team Lead | TRIARQ Health

Mobile: +91.9028136207

Office: +91.253.2344395/96

www.TRIARQhealth.com<http://www.triarqhealth.com/>

    [cid:c0debbb9-3e2e-45a9-b871-9c8a60226dd2]

 This e-mail message and any documents attached to it are confidential and may contain information that is protected from disclosure by various federal and state laws, including the HIPAA privacy rule (45 C.F.R., Part 164). This information is intended to be used solely by the entity or individual to whom this message is addressed. If you are not the intended recipient, be advised that any use, dissemination, forwarding, printing, or copying of this message without the sender's written permission is strictly prohibited and may be unlawful. Accordingly, if you have received this message in error, please notify the sender immediately by phone at 1.877.456.3671, and then delete this message.



________________________________

**Comment by parthea** [comment]
If I understand correctly, the request here is to bump the minimum version of `pyarrow` for this client library to a version greater than `12.0.1`. Based on initial research, it looks like `14.0.1` is the recommended version.

Change
https://github.com/googleapis/python-db-dtypes-pandas/blob/61f6030b37bc5af1defe86c885580116babca10c/setup.py#L34

to

```
 "pyarrow>=14.0.1", 
```

**Comment by parthea** [comment]
@rakesh-sanyashiv , regrettably the screenshot didn't come through. I only have the text information.

**Comment by rakesh-sanyashiv** [comment]
Please verify and let me know if you have any questions!




Rakesh Sanyashiv

Team Lead | TRIARQ Health

Mobile: +91.9028136207

Office: +91.253.2344395/96

www.TRIARQhealth.com<http://www.triarqhealth.com/>

    [cid:66697ee5-611e-4802-8132-6eb7670c94be]

 This e-mail message and any documents attached to it are confidential and may contain information that is protected from disclosure by various federal and state laws, including the HIPAA privacy rule (45 C.F.R., Part 164). This information is intended to be used solely by the entity or individual to whom this message is addressed. If you are not the intended recipient, be advised that any use, dissemination, forwarding, printing, or copying of this message without the sender's written permission is strictly prohibited and may be unlawful. Accordingly, if you have received this message in error, please notify the sender immediately by phone at 1.877.456.3671, and then delete this message.



________________________________

**Comment by Linchin** [comment]
@rakesh-sanyashiv We still could not see the screenshot. Could you send a link instead of as an email attachment? Or reply using github webpage instead.

**Comment by Linchin** [comment]
@rakesh-sanyashiv I'm also unable to reproduce the issue with a clean python 3.12 environment. Installing `db-dtypes` gives me pyarrow==15.0.1:
```
$ pip list
Package         Version
--------------- -----------
db-dtypes       1.2.0
numpy           1.26.4
packaging       23.2
pandas          2.2.1
pip             24.0
pyarrow         15.0.1
python-dateutil 2.9.0.post0
pytz            2024.1
setuptools      69.1.1
six             1.16.0
tzdata          2024.1
wheel           0.42.0
```

**Comment by Linchin** [comment]
I will close this issue for now, as this appears to be a whitesource related problem. @rakesh-sanyashiv Please let us know if there's anything further we can do to help.

**Comment by rakesh-sanyashiv** [comment]
[like]  Rakesh Sanyashiv reacted to your message:
________________________________
