### ISSUE TITLE
register dtypes with pandas

### ISSUE THREAD

**Issue by tswast** [googleapis/python-db-dtypes-pandas#29]
From: https://pandas.pydata.org/pandas-docs/stable/development/extending.html#extension-types

"If you’re building a library that implements the interface, please publicize it on [Extension data types](https://pandas.pydata.org/pandas-docs/stable/ecosystem.html#ecosystem-extensions)."

**Comment by chalmerlowe** [comment]
Closing. Won't fix.
Looking at ways to deprecate this library at some point in the future.
